import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShieldCheck,ScanSearch,Link2,Image as ImageIcon,Mail,QrCode,LifeBuoy,BookOpen,History,LayoutDashboard,ChevronRight,AlertTriangle,CheckCircle2,LockKeyhole,Globe2,Languages,Menu,X,Send} from 'lucide-react';
import './styles.css';

const API='http://localhost:8000/api';
const demoMessage='Congratulations! You have won ₹50,000. Click this link immediately to claim your reward: http://claim-reward.example/login';
const demoUrl='http://claim-reward.example/login?verify=account';

async function api(path,opts={}){const r=await fetch(API+path,opts); if(!r.ok){const e=await r.json().catch(()=>({detail:'Request failed'}));throw new Error(e.detail||'Request failed')} return r.json()}

function RiskBadge({level}){return <span className={'badge '+(level||'LOW').toLowerCase()}>{level||'LOW'}</span>}
function Stat({label,value,icon:Icon}){return <div className="stat"><div className="stat-icon"><Icon size={18}/></div><div><b>{value}</b><span>{label}</span></div></div>}
function Result({result}){if(!result)return null;return <div className="result-card"><div className="result-head"><div><p className="eyebrow">THREAT ANALYSIS</p><h2>{result.risk_score} / 100</h2></div><RiskBadge level={result.risk_level}/></div><div className="result-grid"><div><label>Threat</label><strong>{result.threat_type}</strong></div><div><label>Confidence</label><strong>{result.confidence||'Moderate'}</strong></div></div><section><h3>Why we flagged it</h3><ul className="findings">{(result.indicators||[]).map((x,i)=><li key={i}><AlertTriangle size={16}/>{x}</li>)}</ul></section><section><h3>What you should do</h3><ul className="actions">{(result.recommended_actions||[]).map((x,i)=><li key={i}><CheckCircle2 size={16}/>{x}</li>)}</ul></section>{result.technical_indicators?.length>0&&<details><summary>Technical indicators</summary><p>{result.technical_indicators.join(' • ')}</p></details>}<div className="feedback"><span>Was this analysis helpful?</span><button onClick={()=>api('/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis_id:result.analysis_id,helpful:true})})}>👍 Yes</button><button onClick={()=>api('/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis_id:result.analysis_id,helpful:false,issue:'user_reported'})})}>👎 No</button></div><small>{result.disclaimer}</small></div>}

function Analyzer({type}){const [text,setText]=useState(type==='message'?demoMessage:type==='url'?demoUrl:'');const [result,setResult]=useState(null);const [loading,setLoading]=useState(false);const [file,setFile]=useState(null);const config={message:['Message Analyzer','Paste an SMS, WhatsApp, social message, job offer, payment request, or suspicious text.'],url:['URL Safety Analyzer','Enter a URL. ScamShield inspects structure without opening the destination.'],email:['Email Analyzer','Paste the email body and sender context. Never paste passwords or OTPs.'],screenshot:['Screenshot Analyzer','Upload a screenshot. OCR extracts text for defensive analysis.'],qr:['QR Code Safety','Upload a QR image. The destination is decoded but never automatically opened.']}[type];
 const analyze=async()=>{setLoading(true);setResult(null);try{let r;if(['screenshot','qr'].includes(type)){if(!file)throw Error('Choose an image first.');let f=new FormData();f.append('file',file);r=await api('/analyze/'+type,{method:'POST',body:f})}else{r=await api('/analyze/'+type,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(type==='url'?{url:text}:{text})})}setResult(r)}catch(e){alert(e.message)}finally{setLoading(false)}};
 return <div className="page"><div className="page-title"><div><p className="eyebrow">ANALYZE</p><h1>{config[0]}</h1><p>{config[1]}</p></div><div className="privacy"><LockKeyhole size={16}/> Privacy-first processing</div></div><div className="analyzer"><div className="input-panel">{['screenshot','qr'].includes(type)?<label className="drop"><ImageIcon size={42}/><span>{file?file.name:'Choose image'}</span><small>PNG, JPEG or WebP • max 5 MB</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0])}/></label>:<><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={type==='url'?'https://...':'Paste content here...'} />{type==='message'&&<button className="ghost" onClick={()=>setText(demoMessage)}>Load demo example</button>}{type==='url'&&<button className="ghost" onClick={()=>setText(demoUrl)}>Load demo URL</button>}</>}<button className="primary" onClick={analyze} disabled={loading}>{loading?'Analyzing…':'Analyze safely'}<Send size={17}/></button><p className="safe-note">Never enter passwords, OTPs, PINs, CVVs, recovery codes, or banking credentials.</p></div><Result result={result}/></div></div>}

function Dashboard(){const [data,setData]=useState(null);useEffect(()=>{api('/dashboard').then(setData).catch(()=>setData({scans:0,high_risk:0,critical:0,phishing:0,suspicious_urls:0,security_score:78,recent:[]}))},[]);return <div className="page"><div className="page-title"><div><p className="eyebrow">OVERVIEW</p><h1>Your Digital Safety</h1><p>Understand threats, make safer decisions, and recover quickly.</p></div><div className="score"><span>Safety Score</span><b>{data?.security_score??78}</b><small>/100</small></div></div><div className="stats"><Stat label="Total scans" value={data?.scans??0} icon={ScanSearch}/><Stat label="High risk" value={data?.high_risk??0} icon={AlertTriangle}/><Stat label="Potential phishing" value={data?.phishing??0} icon={ShieldCheck}/><Stat label="Suspicious URLs" value={data?.suspicious_urls??0} icon={Link2}/></div><div className="dashboard-grid"><div className="card"><div className="card-title"><h2>Recent activity</h2><span>Latest analyses</span></div>{data?.recent?.length?data.recent.map((r,i)=><div className="activity" key={i}><div><strong>{r.title}</strong><span>{r.threat}</span></div><RiskBadge level={r.risk_level}/></div>):<div className="empty"><ScanSearch/><p>No analyses yet.</p><span>Try Demo Mode to populate your dashboard.</span></div>}</div><div className="card education-card"><p className="eyebrow">TODAY'S TIP</p><h2>Verify before you trust.</h2><p>Open a bank, employer, delivery company, or payment provider through an app or address you already know instead of using an unsolicited link.</p><div className="tip-row"><CheckCircle2/> Your score is an educational indicator, not a guarantee of security.</div></div></div></div>}

function Incident(){const [action,setAction]=useState('password');const [steps,setSteps]=useState([]);const run=()=>api('/incident-response',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})}).then(r=>setSteps(r.steps));const options=[['clicked','I clicked the link'],['password','I entered my password'],['otp','I shared an OTP'],['banking','I entered banking/card information'],['download','I downloaded a file'],['app','I installed an application'],['payment','I made a payment'],['unknown','I am not sure']];return <div className="page"><div className="page-title"><div><p className="eyebrow">RECOVER</p><h1>I Already Clicked It</h1><p>Get immediate, defensive next steps without submitting any secret credentials.</p></div></div><div className="incident"><div className="option-list">{options.map(([v,l])=><button className={action===v?'selected':''} onClick={()=>setAction(v)} key={v}>{l}<ChevronRight size={17}/></button>)}</div><div className="card recovery"><h2>Your recovery checklist</h2><button className="primary" onClick={run}>Generate safe steps</button>{steps.length>0&&<ol>{steps.map((s,i)=><li key={i}>{s}</li>)}</ol>}<div className="warning"><LockKeyhole/> Never submit actual passwords, OTPs, PINs, CVVs, or recovery codes here.</div></div></div></div>}

function Education(){const qs=[['Your bank says your account will be blocked in 10 minutes and asks you to click a link. What should you do?',['Click immediately','Share OTP','Verify through the official banking app'],2],['A recruiter asks for a registration fee before an interview. What is the safer response?',['Pay quickly to reserve the slot','Verify the employer independently','Send your card details'],1]];return <div className="page"><div className="page-title"><div><p className="eyebrow">LEARN</p><h1>Cyber Safety Center</h1><p>Short lessons that make everyday digital decisions safer.</p></div></div><div className="lesson-grid">{['How phishing works','Fake website detection','OTP safety','Password & MFA safety','QR-code scams','Job scams','Investment scams','Social engineering','Safe online payments'].map((x,i)=><div className="lesson" key={x}><div className="lesson-icon">{i%3===0?<ShieldCheck/>:i%3===1?<LockKeyhole/>:<Globe2/>}</div><h3>{x}</h3><p>Learn the warning signs and one practical action you can use today.</p></div>)}</div><div className="card quiz"><p className="eyebrow">QUICK QUIZ</p><h2>Can you spot the safer decision?</h2>{qs.map(([q,opts,correct],i)=><Quiz key={i} q={q} opts={opts} correct={correct}/>)}</div></div>}
function Quiz({q,opts,correct}){const [sel,setSel]=useState(null);return <div className="q"><strong>{q}</strong><div>{opts.map((o,i)=><button key={o} onClick={()=>setSel(i)} className={sel===i?(i===correct?'right':'wrong'):''}>{o}</button>)}</div>{sel!==null&&<small>{sel===correct?'Correct — verify independently through a known official channel.':'Not the safest choice. Pause and verify through a trusted official channel.'}</small>}</div>}


function HistoryPage(){const [rows,setRows]=useState([]);useEffect(()=>{api('/history').then(setRows).catch(()=>setRows([]))},[]);return <div className="page"><div className="page-title"><div><p className="eyebrow">HISTORY</p><h1>Analysis History</h1><p>Recent analysis metadata only. Sensitive content is not shown here.</p></div></div><div className="card"><div className="history-table"><div className="history-head"><span>Type</span><span>Threat</span><span>Risk</span><span>Date</span></div>{rows.length?rows.map(r=><div className="history-row" key={r.id}><span>{r.kind}</span><span>{r.threat_type}</span><RiskBadge level={r.risk_level}/><span>{new Date(r.created_at).toLocaleString()}</span></div>):<div className="empty"><History/><p>No analysis history yet.</p><span>Run an analysis to see metadata here.</span></div>}</div></div></div>}
function SettingsPage(){return <div className="page"><div className="page-title"><div><p className="eyebrow">SETTINGS</p><h1>Privacy & Safety</h1><p>Prototype controls and deployment guidance.</p></div></div><div className="settings-grid"><div className="card"><h2>Privacy by design</h2><p>ScamShield AI does not request passwords, OTPs, PINs, CVVs, recovery codes or banking credentials.</p><div className="setting-line"><CheckCircle2/> URLs are analyzed as strings; destinations are not automatically opened.</div><div className="setting-line"><CheckCircle2/> Uploaded files are type/size checked and never executed.</div><div className="setting-line"><CheckCircle2/> Dashboard/history stores minimal analysis metadata.</div></div><div className="card"><h2>Prototype limitations</h2><p>Risk scores can have false positives and false negatives. Reputation and domain-age checks require an approved external service.</p><div className="setting-line"><AlertTriangle/> Do not use this prototype as a substitute for a bank, law enforcement, antivirus, or professional incident-response team.</div></div></div></div>}

function Demo({go}){return <div className="demo"><div><span className="demo-pill">⚡ HACKATHON DEMO MODE</span><h2>See ScamShield AI in action.</h2><p>Run a safe, preloaded example without entering real personal information.</p></div><button className="primary" onClick={()=>go('message')}>Try Demo <ChevronRight/></button></div>}

function App(){const [page,setPage]=useState('dashboard');const [mobile,setMobile]=useState(false);const [lang,setLang]=useState('en');const labels={en:{dash:'Dashboard',message:'Message Analyzer',url:'URL Analyzer',shot:'Screenshot',email:'Email Analyzer',qr:'QR Safety',incident:'Incident Response',education:'Safety Center',tag:'Detect. Understand. Protect.'},hi:{dash:'डैशबोर्ड',message:'संदेश विश्लेषक',url:'URL विश्लेषक',shot:'स्क्रीनशॉट',email:'ईमेल विश्लेषक',qr:'QR सुरक्षा',incident:'घटना प्रतिक्रिया',education:'सुरक्षा केंद्र',tag:'पहचानें। समझें। सुरक्षित रहें।'},mr:{dash:'डॅशबोर्ड',message:'संदेश विश्लेषक',url:'URL विश्लेषक',shot:'स्क्रीनशॉट',email:'ईमेल विश्लेषक',qr:'QR सुरक्षा',incident:'घटना प्रतिसाद',education:'सुरक्षा केंद्र',tag:'ओळखा. समजा. सुरक्षित रहा.'}}[lang];const nav=[['dashboard',labels.dash,LayoutDashboard],['message',labels.message,ScanSearch],['url',labels.url,Link2],['screenshot',labels.shot,ImageIcon],['email',labels.email,Mail],['qr',labels.qr,QrCode],['incident',labels.incident,LifeBuoy],['education',labels.education,BookOpen],['history','History',History],['settings','Settings',LockKeyhole]];const content=page==='dashboard'?<Dashboard/>:page==='incident'?<Incident/>:page==='education'?<Education/>:page==='history'?<HistoryPage/>:page==='settings'?<SettingsPage/>:<Analyzer type={page}/>;return <div className="app"><aside className={mobile?'open':''}><div className="brand"><div className="logo"><ShieldCheck/></div><div><b>ScamShield <em>AI</em></b><small>{labels.tag}</small></div></div><nav>{nav.map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>{setPage(id);setMobile(false)}} key={id}><Icon size={18}/>{label}</button>)}</nav><div className="side-bottom"><div className="lang-picker"><Languages size={15}/><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="hi">हिन्दी</option><option value="mr">मराठी</option></select></div><span><LockKeyhole size={14}/> Privacy by design</span></div></aside><main><header><button className="menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div className="crumb">ScamShield AI <ChevronRight size={14}/> {nav.find(x=>x[0]===page)?.[1]||'Dashboard'}</div><button className="demo-nav" onClick={()=>setPage('message')}>Try Demo</button></header>{page==='dashboard'&&<Demo go={setPage}/>} {content}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);
